### ISSUE TITLE
Gaussian Head training loading images with padding/offset

### ISSUE THREAD

**Issue by CscotfordMV** [YuelangX/Gaussian-Head-Avatar#28]
I've managed to train the MeshHead on some custom data and it worked really well, results looked great. However, when I try and train the GaussianHead model afterwards, it seems all the results saved (and I presume the images it's loading in) are being saved with a large amount of padding around the top and left side so the image is shifted a great deal being replaced with just black. I believe I have edited the configs correctly (very little actually as I started with the same resolution size as the mini_demo_dataset - 2080x2080). I should add too that the code works perfectly well with the mini-demo-dataset you provide so the issue isn't any changes I have made myself. Where is this padding coming from?

<img width="326" alt="Screenshot 2024-05-26 at 10 26 03" src="https://github.com/YuelangX/Gaussian-Head-Avatar/assets/114931436/75cd0611-e981-4000-94dc-a60b49369ecb">

**Comment by YuelangX** [comment]
Since the code of the Gaussian renderer is copied from 3D Gaussian Splatting, I cropped the image and modified the intrinsic in lib.dataset.Dataset.GaussianDataset, so that the camera principal point is at the center of the image. I plan to remove this unnecessary operation in the next few days.

**Comment by CscotfordMV** [comment]
Thanks for the quick response!

I can see the code in lib.dataset.Dataset closely resembled the code in preprocess_nersemble. If I were to remove the extra cropping and resizing in the dataset loader, do you expect this to solve the issue, or is there other things at play I should be aware of?

**Comment by NikoBele1** [comment]
@CscotfordMV How did you extract the camera parameters of your custom data? When i train on my custom data, with camera parameters extracted via reality capture, the train_meshhead step fails and throws the error:  `Calculated` padded input size per channel: (0). Kernel size: (1). Kernel size can't be greater than actual input size`
All my input sizes are the same as in the demo dataset, so i thought it may be a problem with the camera parameters, that cause problems downstream. When i plot my vertices from subject/params/*/vertices.npy i can see their orientation being wrong compared to the demo data

**Comment by YuelangX** [comment]
@NikoBele1 I use the camera parameters provided by the NeRSemble data. I guess they are calibrated using checkerboard by the opencv function. If the camera parameters are wrong, it may be caused by inconsistent coordinate systems.
