### ISSUE TITLE
Processing Dataset

### ISSUE THREAD

**Issue by gaga0714** [YuelangX/Gaussian-Head-Avatar#37]
Hello, I downloaded `participant_210.zip`, `camera_params.zip` and `sequence_BACKGROUND_part-1.zip` from the `download_links_nersemble.txt` and processed them according to the following steps. The obtained dataset has a large capacity, reaching `32.7GB`. However, I observed that the `031` and `036` dataset in the `mini demo dataset` you provided was only about `3G` and `6G`. Can you tell me which step might have gone wrong?
![image](https://github.com/user-attachments/assets/3e61f694-a996-4ca4-8a7a-6583dd79a16f)

**Comment by saralkun** [comment]
> Hello, I downloaded `participant_210.zip`, `camera_params.zip` and `sequence_BACKGROUND_part-1.zip` from the `download_links_nersemble.txt` and processed them according to the following steps. The obtained dataset has a large capacity, reaching `32.7GB`. However, I observed that the `031` and `036` dataset in the `mini demo dataset` you provided was only about `3G` and `6G`. Can you tell me which step might have gone wrong? ![image](https://private-user-images.githubusercontent.com/140368447/351978080-3e61f694-a996-4ca4-8a7a-6583dd79a16f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MjcxMjQsIm5iZiI6MTczNjgyNjgyNCwicGF0aCI6Ii8xNDAzNjg0NDcvMzUxOTc4MDgwLTNlNjFmNjk0LWE5OTYtNGNhNC04YTdhLTY1ODNkZDc5YTE2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNFQwMzUzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODhkYzVmYzU4NDg0ZTAxZDNmMDhmZmNjMjRjMTM2YWVhY2VmNjg5MmFjNWZiNTcyNTZkM2Y5ZTNmY2E1MGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YJgtjnEyV6otDi5RLUXwAn64XyCsmc7QjYM4bDZ4f68)

hello，May I ask how you solved this problem?
