### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by Syndulla** [YuelangX/Gaussian-Head-Avatar#9]
Hi Chaps,

This work looks excellent, thank you for sharing. I was hoping to get this up and running on Windows, but before I make an attempt I thought I'd ask how much of an uphill battle you thought that might be?

Thanks in advance for any assistance.

All the best.

**Comment by YuelangX** [comment]
I think it should be OK if you successfully run 3D Gaussian Splatting on Windows.

**Comment by Syndulla** [comment]
Looks like there are a bunch of dependencies in the yaml file which are incompatible sadly!

**Comment by YuelangX** [comment]
Indeed. I recommend that you could manually install the appropriate version of pytorch, pytorch3d, kaolin, etc.

**Comment by Syndulla** [comment]
Absolutely - will give it a go and share if I reach a set of requirements working for windows. Will close this for now.
